// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.26.1
// source: events/builtin/v1/builtin.proto

package v1

import (
	v1 "github.com/knita-io/knita/api/executor/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeTenderStartEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildId  string   `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	TenderId string   `protobuf:"bytes,2,opt,name=tender_id,json=tenderId,proto3" json:"tender_id,omitempty"`
	Opts     *v1.Opts `protobuf:"bytes,3,opt,name=opts,proto3" json:"opts,omitempty"`
}

func (x *RuntimeTenderStartEvent) Reset() {
	*x = RuntimeTenderStartEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeTenderStartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeTenderStartEvent) ProtoMessage() {}

func (x *RuntimeTenderStartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeTenderStartEvent.ProtoReflect.Descriptor instead.
func (*RuntimeTenderStartEvent) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{0}
}

func (x *RuntimeTenderStartEvent) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *RuntimeTenderStartEvent) GetTenderId() string {
	if x != nil {
		return x.TenderId
	}
	return ""
}

func (x *RuntimeTenderStartEvent) GetOpts() *v1.Opts {
	if x != nil {
		return x.Opts
	}
	return nil
}

type RuntimeTenderEndEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenderId string `protobuf:"bytes,1,opt,name=tender_id,json=tenderId,proto3" json:"tender_id,omitempty"` // TODO contracts (need events to be in their own package to avoid circular dependency on broker)
}

func (x *RuntimeTenderEndEvent) Reset() {
	*x = RuntimeTenderEndEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeTenderEndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeTenderEndEvent) ProtoMessage() {}

func (x *RuntimeTenderEndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeTenderEndEvent.ProtoReflect.Descriptor instead.
func (*RuntimeTenderEndEvent) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeTenderEndEvent) GetTenderId() string {
	if x != nil {
		return x.TenderId
	}
	return ""
}

type RuntimeSettlementStartEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenderId   string `protobuf:"bytes,1,opt,name=tender_id,json=tenderId,proto3" json:"tender_id,omitempty"`
	ContractId string `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	RuntimeId  string `protobuf:"bytes,3,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
}

func (x *RuntimeSettlementStartEvent) Reset() {
	*x = RuntimeSettlementStartEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeSettlementStartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeSettlementStartEvent) ProtoMessage() {}

func (x *RuntimeSettlementStartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeSettlementStartEvent.ProtoReflect.Descriptor instead.
func (*RuntimeSettlementStartEvent) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{2}
}

func (x *RuntimeSettlementStartEvent) GetTenderId() string {
	if x != nil {
		return x.TenderId
	}
	return ""
}

func (x *RuntimeSettlementStartEvent) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *RuntimeSettlementStartEvent) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

type RuntimeSettlementEndEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenderId   string `protobuf:"bytes,1,opt,name=tender_id,json=tenderId,proto3" json:"tender_id,omitempty"`
	ContractId string `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	RuntimeId  string `protobuf:"bytes,3,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
}

func (x *RuntimeSettlementEndEvent) Reset() {
	*x = RuntimeSettlementEndEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeSettlementEndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeSettlementEndEvent) ProtoMessage() {}

func (x *RuntimeSettlementEndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeSettlementEndEvent.ProtoReflect.Descriptor instead.
func (*RuntimeSettlementEndEvent) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{3}
}

func (x *RuntimeSettlementEndEvent) GetTenderId() string {
	if x != nil {
		return x.TenderId
	}
	return ""
}

func (x *RuntimeSettlementEndEvent) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *RuntimeSettlementEndEvent) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

type RuntimeOpenStartEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuntimeId string   `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	Opts      *v1.Opts `protobuf:"bytes,2,opt,name=opts,proto3" json:"opts,omitempty"`
}

func (x *RuntimeOpenStartEvent) Reset() {
	*x = RuntimeOpenStartEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeOpenStartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeOpenStartEvent) ProtoMessage() {}

func (x *RuntimeOpenStartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeOpenStartEvent.ProtoReflect.Descriptor instead.
func (*RuntimeOpenStartEvent) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{4}
}

func (x *RuntimeOpenStartEvent) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *RuntimeOpenStartEvent) GetOpts() *v1.Opts {
	if x != nil {
		return x.Opts
	}
	return nil
}

type RuntimeOpenEndEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuntimeId string `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
}

func (x *RuntimeOpenEndEvent) Reset() {
	*x = RuntimeOpenEndEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeOpenEndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeOpenEndEvent) ProtoMessage() {}

func (x *RuntimeOpenEndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeOpenEndEvent.ProtoReflect.Descriptor instead.
func (*RuntimeOpenEndEvent) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{5}
}

func (x *RuntimeOpenEndEvent) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

type RuntimeCloseStartEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuntimeId string `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
}

func (x *RuntimeCloseStartEvent) Reset() {
	*x = RuntimeCloseStartEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeCloseStartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeCloseStartEvent) ProtoMessage() {}

func (x *RuntimeCloseStartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeCloseStartEvent.ProtoReflect.Descriptor instead.
func (*RuntimeCloseStartEvent) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{6}
}

func (x *RuntimeCloseStartEvent) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

type RuntimeCloseEndEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuntimeId string `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
}

func (x *RuntimeCloseEndEvent) Reset() {
	*x = RuntimeCloseEndEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeCloseEndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeCloseEndEvent) ProtoMessage() {}

func (x *RuntimeCloseEndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeCloseEndEvent.ProtoReflect.Descriptor instead.
func (*RuntimeCloseEndEvent) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{7}
}

func (x *RuntimeCloseEndEvent) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

type StdoutEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   []byte          `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Source *LogEventSource `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *StdoutEvent) Reset() {
	*x = StdoutEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StdoutEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdoutEvent) ProtoMessage() {}

func (x *StdoutEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdoutEvent.ProtoReflect.Descriptor instead.
func (*StdoutEvent) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{8}
}

func (x *StdoutEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StdoutEvent) GetSource() *LogEventSource {
	if x != nil {
		return x.Source
	}
	return nil
}

type StderrEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data   []byte          `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Source *LogEventSource `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *StderrEvent) Reset() {
	*x = StderrEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StderrEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StderrEvent) ProtoMessage() {}

func (x *StderrEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StderrEvent.ProtoReflect.Descriptor instead.
func (*StderrEvent) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{9}
}

func (x *StderrEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StderrEvent) GetSource() *LogEventSource {
	if x != nil {
		return x.Source
	}
	return nil
}

type LogEventSource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Source:
	//
	//	*LogEventSource_Runtime
	//	*LogEventSource_Exec
	//	*LogEventSource_Director
	Source isLogEventSource_Source `protobuf_oneof:"source"`
}

func (x *LogEventSource) Reset() {
	*x = LogEventSource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogEventSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEventSource) ProtoMessage() {}

func (x *LogEventSource) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEventSource.ProtoReflect.Descriptor instead.
func (*LogEventSource) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{10}
}

func (m *LogEventSource) GetSource() isLogEventSource_Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (x *LogEventSource) GetRuntime() *LogSourceRuntime {
	if x, ok := x.GetSource().(*LogEventSource_Runtime); ok {
		return x.Runtime
	}
	return nil
}

func (x *LogEventSource) GetExec() *LogSourceExec {
	if x, ok := x.GetSource().(*LogEventSource_Exec); ok {
		return x.Exec
	}
	return nil
}

func (x *LogEventSource) GetDirector() *LogSourceDirector {
	if x, ok := x.GetSource().(*LogEventSource_Director); ok {
		return x.Director
	}
	return nil
}

type isLogEventSource_Source interface {
	isLogEventSource_Source()
}

type LogEventSource_Runtime struct {
	Runtime *LogSourceRuntime `protobuf:"bytes,2,opt,name=runtime,proto3,oneof"`
}

type LogEventSource_Exec struct {
	Exec *LogSourceExec `protobuf:"bytes,3,opt,name=exec,proto3,oneof"`
}

type LogEventSource_Director struct {
	Director *LogSourceDirector `protobuf:"bytes,4,opt,name=director,proto3,oneof"`
}

func (*LogEventSource_Runtime) isLogEventSource_Source() {}

func (*LogEventSource_Exec) isLogEventSource_Source() {}

func (*LogEventSource_Director) isLogEventSource_Source() {}

type LogSourceRuntime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuntimeId string `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
}

func (x *LogSourceRuntime) Reset() {
	*x = LogSourceRuntime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogSourceRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSourceRuntime) ProtoMessage() {}

func (x *LogSourceRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSourceRuntime.ProtoReflect.Descriptor instead.
func (*LogSourceRuntime) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{11}
}

func (x *LogSourceRuntime) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

type LogSourceExec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuntimeId string `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	ExecId    string `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	// System is true if a knita component wrote the log.
	System bool `protobuf:"varint,3,opt,name=system,proto3" json:"system,omitempty"`
}

func (x *LogSourceExec) Reset() {
	*x = LogSourceExec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogSourceExec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSourceExec) ProtoMessage() {}

func (x *LogSourceExec) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSourceExec.ProtoReflect.Descriptor instead.
func (*LogSourceExec) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{12}
}

func (x *LogSourceExec) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *LogSourceExec) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *LogSourceExec) GetSystem() bool {
	if x != nil {
		return x.System
	}
	return false
}

type LogSourceDirector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogSourceDirector) Reset() {
	*x = LogSourceDirector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogSourceDirector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSourceDirector) ProtoMessage() {}

func (x *LogSourceDirector) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSourceDirector.ProtoReflect.Descriptor instead.
func (*LogSourceDirector) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{13}
}

type ExecStartEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuntimeId string            `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	ExecId    string            `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Opts      *v1.ExecOpts      `protobuf:"bytes,3,opt,name=opts,proto3" json:"opts,omitempty"`
	Tags      map[string]string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ExecStartEvent) Reset() {
	*x = ExecStartEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecStartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStartEvent) ProtoMessage() {}

func (x *ExecStartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStartEvent.ProtoReflect.Descriptor instead.
func (*ExecStartEvent) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{14}
}

func (x *ExecStartEvent) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *ExecStartEvent) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *ExecStartEvent) GetOpts() *v1.ExecOpts {
	if x != nil {
		return x.Opts
	}
	return nil
}

func (x *ExecStartEvent) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ImportStartEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuntimeId string `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	ImportId  string `protobuf:"bytes,2,opt,name=import_id,json=importId,proto3" json:"import_id,omitempty"`
}

func (x *ImportStartEvent) Reset() {
	*x = ImportStartEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportStartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportStartEvent) ProtoMessage() {}

func (x *ImportStartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportStartEvent.ProtoReflect.Descriptor instead.
func (*ImportStartEvent) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{15}
}

func (x *ImportStartEvent) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *ImportStartEvent) GetImportId() string {
	if x != nil {
		return x.ImportId
	}
	return ""
}

type ImportEndEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuntimeId string `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	ImportId  string `protobuf:"bytes,2,opt,name=import_id,json=importId,proto3" json:"import_id,omitempty"`
}

func (x *ImportEndEvent) Reset() {
	*x = ImportEndEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportEndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportEndEvent) ProtoMessage() {}

func (x *ImportEndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportEndEvent.ProtoReflect.Descriptor instead.
func (*ImportEndEvent) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{16}
}

func (x *ImportEndEvent) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *ImportEndEvent) GetImportId() string {
	if x != nil {
		return x.ImportId
	}
	return ""
}

type ExportStartEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuntimeId string `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	ExportId  string `protobuf:"bytes,2,opt,name=export_id,json=exportId,proto3" json:"export_id,omitempty"`
}

func (x *ExportStartEvent) Reset() {
	*x = ExportStartEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportStartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportStartEvent) ProtoMessage() {}

func (x *ExportStartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportStartEvent.ProtoReflect.Descriptor instead.
func (*ExportStartEvent) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{17}
}

func (x *ExportStartEvent) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *ExportStartEvent) GetExportId() string {
	if x != nil {
		return x.ExportId
	}
	return ""
}

type ExportEndEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuntimeId string `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	ExportId  string `protobuf:"bytes,2,opt,name=export_id,json=exportId,proto3" json:"export_id,omitempty"`
}

func (x *ExportEndEvent) Reset() {
	*x = ExportEndEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportEndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportEndEvent) ProtoMessage() {}

func (x *ExportEndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportEndEvent.ProtoReflect.Descriptor instead.
func (*ExportEndEvent) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{18}
}

func (x *ExportEndEvent) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *ExportEndEvent) GetExportId() string {
	if x != nil {
		return x.ExportId
	}
	return ""
}

type ExecEndEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuntimeId string `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	ExecId    string `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Error     string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // TODO structured error?
	ExitCode  int32  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
}

func (x *ExecEndEvent) Reset() {
	*x = ExecEndEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecEndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecEndEvent) ProtoMessage() {}

func (x *ExecEndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecEndEvent.ProtoReflect.Descriptor instead.
func (*ExecEndEvent) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{19}
}

func (x *ExecEndEvent) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *ExecEndEvent) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *ExecEndEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecEndEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type SyncPointReachedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarrierId string `protobuf:"bytes,1,opt,name=barrier_id,json=barrierId,proto3" json:"barrier_id,omitempty"`
}

func (x *SyncPointReachedEvent) Reset() {
	*x = SyncPointReachedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_builtin_v1_builtin_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncPointReachedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPointReachedEvent) ProtoMessage() {}

func (x *SyncPointReachedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_builtin_v1_builtin_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPointReachedEvent.ProtoReflect.Descriptor instead.
func (*SyncPointReachedEvent) Descriptor() ([]byte, []int) {
	return file_events_builtin_v1_builtin_proto_rawDescGZIP(), []int{20}
}

func (x *SyncPointReachedEvent) GetBarrierId() string {
	if x != nil {
		return x.BarrierId
	}
	return ""
}

var File_events_builtin_v1_builtin_proto protoreflect.FileDescriptor

var file_events_builtin_v1_builtin_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e,
	0x2f, 0x76, 0x31, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x17, 0x62, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x6b, 0x6e, 0x69, 0x74, 0x61, 0x2e, 0x69, 0x6f, 0x1a, 0x1a, 0x65, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x6f, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x17, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x04, 0x6f, 0x70, 0x74,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x6f, 0x72, 0x2e, 0x6b, 0x6e, 0x69, 0x74, 0x61, 0x2e, 0x69, 0x6f, 0x2e, 0x4f, 0x70, 0x74, 0x73,
	0x52, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x22, 0x34, 0x0a, 0x15, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x7a, 0x0a, 0x1b,
	0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x78, 0x0a, 0x19, 0x52, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x64,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x49, 0x64, 0x22, 0x63, 0x0a, 0x15, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x4f, 0x70, 0x65,
	0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x04, 0x6f, 0x70,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x6f, 0x72, 0x2e, 0x6b, 0x6e, 0x69, 0x74, 0x61, 0x2e, 0x69, 0x6f, 0x2e, 0x4f, 0x70, 0x74,
	0x73, 0x52, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x22, 0x34, 0x0a, 0x13, 0x52, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x45, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x37, 0x0a,
	0x16, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x14, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x45, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x62, 0x0a,
	0x0b, 0x53, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x3f, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x27, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x6b, 0x6e, 0x69, 0x74, 0x61, 0x2e, 0x69, 0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x22, 0x62, 0x0a, 0x0b, 0x53, 0x74, 0x64, 0x65, 0x72, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x3f, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x2e, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x6b, 0x6e, 0x69, 0x74, 0x61, 0x2e, 0x69, 0x6f, 0x2e, 0x4c,
	0x6f, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0xe9, 0x01, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x62, 0x75, 0x69, 0x6c,
	0x74, 0x69, 0x6e, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x6b, 0x6e, 0x69, 0x74, 0x61,
	0x2e, 0x69, 0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x3c, 0x0a, 0x04, 0x65, 0x78, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x62, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x6b,
	0x6e, 0x69, 0x74, 0x61, 0x2e, 0x69, 0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x45, 0x78, 0x65, 0x63, 0x48, 0x00, 0x52, 0x04, 0x65, 0x78, 0x65, 0x63, 0x12, 0x48, 0x0a,
	0x08, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2a, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x6b, 0x6e, 0x69, 0x74, 0x61, 0x2e, 0x69, 0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x08, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x22, 0x31, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x49, 0x64, 0x22, 0x5f, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x45, 0x78, 0x65, 0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x78, 0x65, 0x63, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x78, 0x65, 0x63, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0xf9, 0x01, 0x0a, 0x0e, 0x45,
	0x78, 0x65, 0x63, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x65, 0x78, 0x65, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65,
	0x78, 0x65, 0x63, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x2e, 0x6b,
	0x6e, 0x69, 0x74, 0x61, 0x2e, 0x69, 0x6f, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x4f, 0x70, 0x74, 0x73,
	0x52, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x12, 0x45, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x2e, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x6b, 0x6e, 0x69, 0x74, 0x61, 0x2e, 0x69, 0x6f, 0x2e, 0x45,
	0x78, 0x65, 0x63, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x61,
	0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x1a, 0x37, 0x0a,
	0x09, 0x54, 0x61, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x4e, 0x0a, 0x10, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x0e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x45, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x10, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x0e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x6e,
	0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x49, 0x64, 0x22, 0x79, 0x0a, 0x0c, 0x45, 0x78, 0x65, 0x63, 0x45, 0x6e, 0x64, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x78, 0x65, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x65, 0x78, 0x65, 0x63, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x36, 0x0a,
	0x15, 0x53, 0x79, 0x6e, 0x63, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x61, 0x63, 0x68, 0x65,
	0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x72, 0x72, 0x69, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x61, 0x72, 0x72,
	0x69, 0x65, 0x72, 0x49, 0x64, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6e, 0x69, 0x74, 0x61, 0x2d, 0x69, 0x6f, 0x2f, 0x6b, 0x6e, 0x69,
	0x74, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x62, 0x75,
	0x69, 0x6c, 0x74, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_events_builtin_v1_builtin_proto_rawDescOnce sync.Once
	file_events_builtin_v1_builtin_proto_rawDescData = file_events_builtin_v1_builtin_proto_rawDesc
)

func file_events_builtin_v1_builtin_proto_rawDescGZIP() []byte {
	file_events_builtin_v1_builtin_proto_rawDescOnce.Do(func() {
		file_events_builtin_v1_builtin_proto_rawDescData = protoimpl.X.CompressGZIP(file_events_builtin_v1_builtin_proto_rawDescData)
	})
	return file_events_builtin_v1_builtin_proto_rawDescData
}

var file_events_builtin_v1_builtin_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_events_builtin_v1_builtin_proto_goTypes = []interface{}{
	(*RuntimeTenderStartEvent)(nil),     // 0: builtin.events.knita.io.RuntimeTenderStartEvent
	(*RuntimeTenderEndEvent)(nil),       // 1: builtin.events.knita.io.RuntimeTenderEndEvent
	(*RuntimeSettlementStartEvent)(nil), // 2: builtin.events.knita.io.RuntimeSettlementStartEvent
	(*RuntimeSettlementEndEvent)(nil),   // 3: builtin.events.knita.io.RuntimeSettlementEndEvent
	(*RuntimeOpenStartEvent)(nil),       // 4: builtin.events.knita.io.RuntimeOpenStartEvent
	(*RuntimeOpenEndEvent)(nil),         // 5: builtin.events.knita.io.RuntimeOpenEndEvent
	(*RuntimeCloseStartEvent)(nil),      // 6: builtin.events.knita.io.RuntimeCloseStartEvent
	(*RuntimeCloseEndEvent)(nil),        // 7: builtin.events.knita.io.RuntimeCloseEndEvent
	(*StdoutEvent)(nil),                 // 8: builtin.events.knita.io.StdoutEvent
	(*StderrEvent)(nil),                 // 9: builtin.events.knita.io.StderrEvent
	(*LogEventSource)(nil),              // 10: builtin.events.knita.io.LogEventSource
	(*LogSourceRuntime)(nil),            // 11: builtin.events.knita.io.LogSourceRuntime
	(*LogSourceExec)(nil),               // 12: builtin.events.knita.io.LogSourceExec
	(*LogSourceDirector)(nil),           // 13: builtin.events.knita.io.LogSourceDirector
	(*ExecStartEvent)(nil),              // 14: builtin.events.knita.io.ExecStartEvent
	(*ImportStartEvent)(nil),            // 15: builtin.events.knita.io.ImportStartEvent
	(*ImportEndEvent)(nil),              // 16: builtin.events.knita.io.ImportEndEvent
	(*ExportStartEvent)(nil),            // 17: builtin.events.knita.io.ExportStartEvent
	(*ExportEndEvent)(nil),              // 18: builtin.events.knita.io.ExportEndEvent
	(*ExecEndEvent)(nil),                // 19: builtin.events.knita.io.ExecEndEvent
	(*SyncPointReachedEvent)(nil),       // 20: builtin.events.knita.io.SyncPointReachedEvent
	nil,                                 // 21: builtin.events.knita.io.ExecStartEvent.TagsEntry
	(*v1.Opts)(nil),                     // 22: executor.knita.io.Opts
	(*v1.ExecOpts)(nil),                 // 23: executor.knita.io.ExecOpts
}
var file_events_builtin_v1_builtin_proto_depIdxs = []int32{
	22, // 0: builtin.events.knita.io.RuntimeTenderStartEvent.opts:type_name -> executor.knita.io.Opts
	22, // 1: builtin.events.knita.io.RuntimeOpenStartEvent.opts:type_name -> executor.knita.io.Opts
	10, // 2: builtin.events.knita.io.StdoutEvent.source:type_name -> builtin.events.knita.io.LogEventSource
	10, // 3: builtin.events.knita.io.StderrEvent.source:type_name -> builtin.events.knita.io.LogEventSource
	11, // 4: builtin.events.knita.io.LogEventSource.runtime:type_name -> builtin.events.knita.io.LogSourceRuntime
	12, // 5: builtin.events.knita.io.LogEventSource.exec:type_name -> builtin.events.knita.io.LogSourceExec
	13, // 6: builtin.events.knita.io.LogEventSource.director:type_name -> builtin.events.knita.io.LogSourceDirector
	23, // 7: builtin.events.knita.io.ExecStartEvent.opts:type_name -> executor.knita.io.ExecOpts
	21, // 8: builtin.events.knita.io.ExecStartEvent.tags:type_name -> builtin.events.knita.io.ExecStartEvent.TagsEntry
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_events_builtin_v1_builtin_proto_init() }
func file_events_builtin_v1_builtin_proto_init() {
	if File_events_builtin_v1_builtin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_events_builtin_v1_builtin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeTenderStartEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeTenderEndEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeSettlementStartEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeSettlementEndEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeOpenStartEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeOpenEndEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeCloseStartEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeCloseEndEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StdoutEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StderrEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogEventSource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogSourceRuntime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogSourceExec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogSourceDirector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecStartEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportStartEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportEndEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportStartEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportEndEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecEndEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_builtin_v1_builtin_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncPointReachedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_events_builtin_v1_builtin_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*LogEventSource_Runtime)(nil),
		(*LogEventSource_Exec)(nil),
		(*LogEventSource_Director)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_events_builtin_v1_builtin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_builtin_v1_builtin_proto_goTypes,
		DependencyIndexes: file_events_builtin_v1_builtin_proto_depIdxs,
		MessageInfos:      file_events_builtin_v1_builtin_proto_msgTypes,
	}.Build()
	File_events_builtin_v1_builtin_proto = out.File
	file_events_builtin_v1_builtin_proto_rawDesc = nil
	file_events_builtin_v1_builtin_proto_goTypes = nil
	file_events_builtin_v1_builtin_proto_depIdxs = nil
}
