# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import broker_pb2 as broker_dot_v1_dot_broker__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in broker/v1/broker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class RuntimeBrokerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Tender = channel.unary_unary(
                '/broker.RuntimeBroker/Tender',
                request_serializer=broker_dot_v1_dot_broker__pb2.RuntimeTender.SerializeToString,
                response_deserializer=broker_dot_v1_dot_broker__pb2.RuntimeContracts.FromString,
                _registered_method=True)
        self.Settle = channel.unary_unary(
                '/broker.RuntimeBroker/Settle',
                request_serializer=broker_dot_v1_dot_broker__pb2.RuntimeContract.SerializeToString,
                response_deserializer=broker_dot_v1_dot_broker__pb2.RuntimeSettlement.FromString,
                _registered_method=True)


class RuntimeBrokerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Tender(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Settle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeBrokerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Tender': grpc.unary_unary_rpc_method_handler(
                    servicer.Tender,
                    request_deserializer=broker_dot_v1_dot_broker__pb2.RuntimeTender.FromString,
                    response_serializer=broker_dot_v1_dot_broker__pb2.RuntimeContracts.SerializeToString,
            ),
            'Settle': grpc.unary_unary_rpc_method_handler(
                    servicer.Settle,
                    request_deserializer=broker_dot_v1_dot_broker__pb2.RuntimeContract.FromString,
                    response_serializer=broker_dot_v1_dot_broker__pb2.RuntimeSettlement.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'broker.RuntimeBroker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RuntimeBroker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Tender(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.RuntimeBroker/Tender',
            broker_dot_v1_dot_broker__pb2.RuntimeTender.SerializeToString,
            broker_dot_v1_dot_broker__pb2.RuntimeContracts.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Settle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.RuntimeBroker/Settle',
            broker_dot_v1_dot_broker__pb2.RuntimeContract.SerializeToString,
            broker_dot_v1_dot_broker__pb2.RuntimeSettlement.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
