# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: broker/v1/broker.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import executor_pb2 as executor_dot_v1_dot_executor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x62roker/v1/broker.proto\x12\x0f\x62roker.knita.io\x1a\x1a\x65xecutor/v1/executor.proto\"b\n\rTenderRequest\x12\x10\n\x08\x62uild_id\x18\x01 \x01(\t\x12\x11\n\ttender_id\x18\x02 \x01(\t\x12,\n\x04opts\x18\x03 \x01(\x0b\x32\x1e.executor.knita.io.RuntimeOpts\"\xe4\x01\n\x0fRuntimeContract\x12\x11\n\ttender_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ontract_id\x18\x02 \x01(\t\x12\x12\n\nruntime_id\x18\x03 \x01(\t\x12,\n\x04opts\x18\x04 \x01(\x0b\x32\x1e.executor.knita.io.RuntimeOpts\x12/\n\x08sys_info\x18\x05 \x01(\x0b\x32\x1d.executor.knita.io.SystemInfo\x12\x36\n\rexecutor_info\x18\x06 \x01(\x0b\x32\x1f.executor.knita.io.ExecutorInfo\"E\n\x0eTenderResponse\x12\x33\n\tcontracts\x18\x01 \x03(\x0b\x32 .broker.knita.io.RuntimeContract\"G\n\x11SettlementRequest\x12\x32\n\x08\x63ontract\x18\x01 \x01(\x0b\x32 .broker.knita.io.RuntimeContract\"U\n\x12SettlementResponse\x12?\n\x0f\x63onnection_info\x18\x01 \x01(\x0b\x32&.broker.knita.io.RuntimeConnectionInfo\"\x90\x01\n\x15RuntimeConnectionInfo\x12\x35\n\x04unix\x18\x01 \x01(\x0b\x32%.broker.knita.io.RuntimeTransportUnixH\x00\x12\x33\n\x03tcp\x18\x02 \x01(\x0b\x32$.broker.knita.io.RuntimeTransportTCPH\x00\x42\x0b\n\ttransport\"+\n\x14RuntimeTransportUnix\x12\x13\n\x0bsocket_path\x18\x01 \x01(\t\"&\n\x13RuntimeTransportTCP\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t2\xa6\x01\n\x06\x42roker\x12I\n\x06Tender\x12\x1e.broker.knita.io.TenderRequest\x1a\x1f.broker.knita.io.TenderResponse\x12Q\n\x06Settle\x12\".broker.knita.io.SettlementRequest\x1a#.broker.knita.io.SettlementResponseB)Z\'github.com/knita-io/knita/api/broker/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'broker.v1.broker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/knita-io/knita/api/broker/v1'
  _globals['_TENDERREQUEST']._serialized_start=71
  _globals['_TENDERREQUEST']._serialized_end=169
  _globals['_RUNTIMECONTRACT']._serialized_start=172
  _globals['_RUNTIMECONTRACT']._serialized_end=400
  _globals['_TENDERRESPONSE']._serialized_start=402
  _globals['_TENDERRESPONSE']._serialized_end=471
  _globals['_SETTLEMENTREQUEST']._serialized_start=473
  _globals['_SETTLEMENTREQUEST']._serialized_end=544
  _globals['_SETTLEMENTRESPONSE']._serialized_start=546
  _globals['_SETTLEMENTRESPONSE']._serialized_end=631
  _globals['_RUNTIMECONNECTIONINFO']._serialized_start=634
  _globals['_RUNTIMECONNECTIONINFO']._serialized_end=778
  _globals['_RUNTIMETRANSPORTUNIX']._serialized_start=780
  _globals['_RUNTIMETRANSPORTUNIX']._serialized_end=823
  _globals['_RUNTIMETRANSPORTTCP']._serialized_start=825
  _globals['_RUNTIMETRANSPORTTCP']._serialized_end=863
  _globals['_BROKER']._serialized_start=866
  _globals['_BROKER']._serialized_end=1032
# @@protoc_insertion_point(module_scope)
