# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import director_pb2 as director_dot_v1_dot_director__pb2
from . import executor_pb2 as executor_dot_v1_dot_executor__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in director/v1/director_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class DirectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Open = channel.unary_unary(
                '/director.Director/Open',
                request_serializer=director_dot_v1_dot_director__pb2.OpenRequest.SerializeToString,
                response_deserializer=director_dot_v1_dot_director__pb2.OpenResponse.FromString,
                _registered_method=True)
        self.Exec = channel.unary_stream(
                '/director.Director/Exec',
                request_serializer=director_dot_v1_dot_director__pb2.ExecRequest.SerializeToString,
                response_deserializer=director_dot_v1_dot_director__pb2.ExecEvent.FromString,
                _registered_method=True)
        self.Import = channel.unary_unary(
                '/director.Director/Import',
                request_serializer=director_dot_v1_dot_director__pb2.ImportRequest.SerializeToString,
                response_deserializer=director_dot_v1_dot_director__pb2.ImportResponse.FromString,
                _registered_method=True)
        self.Export = channel.unary_unary(
                '/director.Director/Export',
                request_serializer=director_dot_v1_dot_director__pb2.ExportRequest.SerializeToString,
                response_deserializer=director_dot_v1_dot_director__pb2.ExportResponse.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/director.Director/Close',
                request_serializer=executor_dot_v1_dot_executor__pb2.CloseRequest.SerializeToString,
                response_deserializer=executor_dot_v1_dot_executor__pb2.CloseResponse.FromString,
                _registered_method=True)


class DirectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Open(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Import(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Export(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DirectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Open': grpc.unary_unary_rpc_method_handler(
                    servicer.Open,
                    request_deserializer=director_dot_v1_dot_director__pb2.OpenRequest.FromString,
                    response_serializer=director_dot_v1_dot_director__pb2.OpenResponse.SerializeToString,
            ),
            'Exec': grpc.unary_stream_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=director_dot_v1_dot_director__pb2.ExecRequest.FromString,
                    response_serializer=director_dot_v1_dot_director__pb2.ExecEvent.SerializeToString,
            ),
            'Import': grpc.unary_unary_rpc_method_handler(
                    servicer.Import,
                    request_deserializer=director_dot_v1_dot_director__pb2.ImportRequest.FromString,
                    response_serializer=director_dot_v1_dot_director__pb2.ImportResponse.SerializeToString,
            ),
            'Export': grpc.unary_unary_rpc_method_handler(
                    servicer.Export,
                    request_deserializer=director_dot_v1_dot_director__pb2.ExportRequest.FromString,
                    response_serializer=director_dot_v1_dot_director__pb2.ExportResponse.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=executor_dot_v1_dot_executor__pb2.CloseRequest.FromString,
                    response_serializer=executor_dot_v1_dot_executor__pb2.CloseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'director.Director', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Director(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Open(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/director.Director/Open',
            director_dot_v1_dot_director__pb2.OpenRequest.SerializeToString,
            director_dot_v1_dot_director__pb2.OpenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/director.Director/Exec',
            director_dot_v1_dot_director__pb2.ExecRequest.SerializeToString,
            director_dot_v1_dot_director__pb2.ExecEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Import(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/director.Director/Import',
            director_dot_v1_dot_director__pb2.ImportRequest.SerializeToString,
            director_dot_v1_dot_director__pb2.ImportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Export(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/director.Director/Export',
            director_dot_v1_dot_director__pb2.ExportRequest.SerializeToString,
            director_dot_v1_dot_director__pb2.ExportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/director.Director/Close',
            executor_dot_v1_dot_executor__pb2.CloseRequest.SerializeToString,
            executor_dot_v1_dot_executor__pb2.CloseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
