# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: observer/v1/observer.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import event_pb2 as events_dot_v1_dot_event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aobserver/v1/observer.proto\x12\x11observer.knita.io\x1a\x15\x65vents/v1/event.proto\"\x0f\n\rWatchResponse2O\n\x08Observer\x12\x43\n\x05Watch\x12\x16.events.knita.io.Event\x1a .observer.knita.io.WatchResponse(\x01\x42+Z)github.com/knita-io/knita/api/observer/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'observer.v1.observer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/knita-io/knita/api/observer/v1'
  _globals['_WATCHRESPONSE']._serialized_start=72
  _globals['_WATCHRESPONSE']._serialized_end=87
  _globals['_OBSERVER']._serialized_start=89
  _globals['_OBSERVER']._serialized_end=168
# @@protoc_insertion_point(module_scope)
