# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: observer/v1/observer.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import executor_pb2 as executor_dot_v1_dot_executor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aobserver/v1/observer.proto\x12\x08observer\x1a\x1a\x65xecutor/v1/executor.proto\"\x0f\n\rWatchResponse2?\n\x08Observer\x12\x33\n\x05Watch\x12\x0f.executor.Event\x1a\x17.observer.WatchResponse(\x01\x42+Z)github.com/knita-io/knita/api/observer/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'observer.v1.observer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/knita-io/knita/api/observer/v1'
  _globals['_WATCHRESPONSE']._serialized_start=68
  _globals['_WATCHRESPONSE']._serialized_end=83
  _globals['_OBSERVER']._serialized_start=85
  _globals['_OBSERVER']._serialized_end=148
# @@protoc_insertion_point(module_scope)
