name: Knita
on: [ push, workflow_dispatch ]
defaults:
  run:
    working-directory: .
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
          cache: true
          cache-dependency-path: go.sum
      - name: Install Knita
        run: go install .
        working-directory: cmd/knita
      - name: Run Knita
        run: knita build ./build/pattern.sh
        env:
          DOCKER_API_VERSION: 1.43
          KNITA_BUILD_DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          KNITA_BUILD_TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          KNITA_CLI_LOG_PATH: /tmp/knita-cli.log
      - name: Capture Knita CLI log
        if: success() || failure()
        run: cat /tmp/knita-cli.log
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Knita Binaries
          path: |
            build/output/cli/*
            build/output/executor/*